apiVersion: v1
kind: ConfigMap
data:
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_CFG_ADVERTISED_LISTENERS: "INSIDE://kafka:9092"
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INSIDE"
  KAFKA_CFG_LISTENERS: "INSIDE://0.0.0.0:9092"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT"
  KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
  ALLOW_ANONYMOUS_LOGIN: "yes"
metadata:
  name: kafka-env
  namespace: udaconnect