apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-locationworker
  name: udaconnect-locationworker
  namespace: udaconnect
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30052
  selector:
    service: udaconnect-locationworker
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locationworker
  name: udaconnect-locationworker
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-locationworker
  template:
    metadata:
      labels:
        service: udaconnect-locationworker
    spec:
      containers:
      - image: jeikens/udaconnect-locationworker:latest
        name: udaconnect-locationworker
        imagePullPolicy: Always
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: API_PORT
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: KAFKA_HOST
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: KAFKA_PORT
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: KAFKA_TOPIC
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      restartPolicy: Always
