apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-locations
  name: udaconnect-locations
  namespace: udaconnect
spec:
  ports:
  - name: "50051"
    port: 50051
    targetPort: 50051
    nodePort: 30051
  selector:
    service: udaconnect-locations
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locations
  name: udaconnect-locations
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-locations
  template:
    metadata:
      labels:
        service: udaconnect-locations
    spec:
      containers:
      - image: jeikens/udaconnect-locations:latest
        name: udaconnect-locations
        imagePullPolicy: Always
        env:
        - name: GRPC_HOST
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: GRPC_HOST
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: GRPC_PORT
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: API_PORT
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: KAFKA_HOST
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: KAFKA_PORT
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: udaconnect-env
              key: KAFKA_TOPIC
      restartPolicy: Always
