# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x0flocationservice\"J\n\x08Location\x12\x0c\n\x04user\x18\x01 \x01(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\x05\x12\x11\n\tlongitude\x18\x03 \x01(\x05\x12\x0b\n\x03utc\x18\x04 \x01(\x05\"\x07\n\x05\x45mpty2V\n\x0fLocationService\x12\x43\n\x0cPushLocation\x12\x19.locationservice.Location\x1a\x16.locationservice.Empty\"\x00\x62\x06proto3')



_LOCATION = DESCRIPTOR.message_types_by_name['Location']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
  'DESCRIPTOR' : _LOCATION,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:locationservice.Location)
  })
_sym_db.RegisterMessage(Location)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:locationservice.Empty)
  })
_sym_db.RegisterMessage(Empty)

_LOCATIONSERVICE = DESCRIPTOR.services_by_name['LocationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATION._serialized_start=35
  _LOCATION._serialized_end=109
  _EMPTY._serialized_start=111
  _EMPTY._serialized_end=118
  _LOCATIONSERVICE._serialized_start=120
  _LOCATIONSERVICE._serialized_end=206
# @@protoc_insertion_point(module_scope)
